// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: linkedca/kms.proto

package linkedca

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KMS_Type int32

const (
	KMS_DEFAULT     KMS_Type = 0
	KMS_SOFTKMS     KMS_Type = 1
	KMS_CLOUDKMS    KMS_Type = 2
	KMS_AMAZONKMS   KMS_Type = 3
	KMS_PKCS11      KMS_Type = 4
	KMS_YUBIKEY     KMS_Type = 5
	KMS_SSHAGENTKMS KMS_Type = 6
	KMS_AZUREKMS    KMS_Type = 7
)

// Enum value maps for KMS_Type.
var (
	KMS_Type_name = map[int32]string{
		0: "DEFAULT",
		1: "SOFTKMS",
		2: "CLOUDKMS",
		3: "AMAZONKMS",
		4: "PKCS11",
		5: "YUBIKEY",
		6: "SSHAGENTKMS",
		7: "AZUREKMS",
	}
	KMS_Type_value = map[string]int32{
		"DEFAULT":     0,
		"SOFTKMS":     1,
		"CLOUDKMS":    2,
		"AMAZONKMS":   3,
		"PKCS11":      4,
		"YUBIKEY":     5,
		"SSHAGENTKMS": 6,
		"AZUREKMS":    7,
	}
)

func (x KMS_Type) Enum() *KMS_Type {
	p := new(KMS_Type)
	*p = x
	return p
}

func (x KMS_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KMS_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_linkedca_kms_proto_enumTypes[0].Descriptor()
}

func (KMS_Type) Type() protoreflect.EnumType {
	return &file_linkedca_kms_proto_enumTypes[0]
}

func (x KMS_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KMS_Type.Descriptor instead.
func (KMS_Type) EnumDescriptor() ([]byte, []int) {
	return file_linkedca_kms_proto_rawDescGZIP(), []int{0, 0}
}

type KMS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            KMS_Type `protobuf:"varint,1,opt,name=type,proto3,enum=linkedca.KMS_Type" json:"type,omitempty"`
	CredentialsFile string   `protobuf:"bytes,2,opt,name=credentialsFile,proto3" json:"credentialsFile,omitempty"`
	Uri             string   `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Pin             string   `protobuf:"bytes,4,opt,name=pin,proto3" json:"pin,omitempty"`
	ManagementKey   string   `protobuf:"bytes,5,opt,name=managementKey,proto3" json:"managementKey,omitempty"`
	Region          string   `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Profile         string   `protobuf:"bytes,7,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *KMS) Reset() {
	*x = KMS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_kms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KMS) ProtoMessage() {}

func (x *KMS) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_kms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KMS.ProtoReflect.Descriptor instead.
func (*KMS) Descriptor() ([]byte, []int) {
	return file_linkedca_kms_proto_rawDescGZIP(), []int{0}
}

func (x *KMS) GetType() KMS_Type {
	if x != nil {
		return x.Type
	}
	return KMS_DEFAULT
}

func (x *KMS) GetCredentialsFile() string {
	if x != nil {
		return x.CredentialsFile
	}
	return ""
}

func (x *KMS) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *KMS) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *KMS) GetManagementKey() string {
	if x != nil {
		return x.ManagementKey
	}
	return ""
}

func (x *KMS) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *KMS) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

var File_linkedca_kms_proto protoreflect.FileDescriptor

var file_linkedca_kms_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2f, 0x6b, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x22, 0xca,
	0x02, 0x0a, 0x03, 0x4b, 0x4d, 0x53, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e,
	0x4b, 0x4d, 0x53, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x46, 0x69, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x22, 0x75, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x4f, 0x46,
	0x54, 0x4b, 0x4d, 0x53, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x4b,
	0x4d, 0x53, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4d, 0x41, 0x5a, 0x4f, 0x4e, 0x4b, 0x4d,
	0x53, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x4b, 0x43, 0x53, 0x31, 0x31, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x59, 0x55, 0x42, 0x49, 0x4b, 0x45, 0x59, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x53, 0x48, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x4b, 0x4d, 0x53, 0x10, 0x06, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x5a, 0x55, 0x52, 0x45, 0x4b, 0x4d, 0x53, 0x10, 0x07, 0x42, 0x15, 0x5a, 0x13, 0x67,
	0x6f, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x2e, 0x73, 0x6d, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x63, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linkedca_kms_proto_rawDescOnce sync.Once
	file_linkedca_kms_proto_rawDescData = file_linkedca_kms_proto_rawDesc
)

func file_linkedca_kms_proto_rawDescGZIP() []byte {
	file_linkedca_kms_proto_rawDescOnce.Do(func() {
		file_linkedca_kms_proto_rawDescData = protoimpl.X.CompressGZIP(file_linkedca_kms_proto_rawDescData)
	})
	return file_linkedca_kms_proto_rawDescData
}

var file_linkedca_kms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_linkedca_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_linkedca_kms_proto_goTypes = []interface{}{
	(KMS_Type)(0), // 0: linkedca.KMS.Type
	(*KMS)(nil),   // 1: linkedca.KMS
}
var file_linkedca_kms_proto_depIdxs = []int32{
	0, // 0: linkedca.KMS.type:type_name -> linkedca.KMS.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_linkedca_kms_proto_init() }
func file_linkedca_kms_proto_init() {
	if File_linkedca_kms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linkedca_kms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KMS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linkedca_kms_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_linkedca_kms_proto_goTypes,
		DependencyIndexes: file_linkedca_kms_proto_depIdxs,
		EnumInfos:         file_linkedca_kms_proto_enumTypes,
		MessageInfos:      file_linkedca_kms_proto_msgTypes,
	}.Build()
	File_linkedca_kms_proto = out.File
	file_linkedca_kms_proto_rawDesc = nil
	file_linkedca_kms_proto_goTypes = nil
	file_linkedca_kms_proto_depIdxs = nil
}
